name: Deploy Project
on: push
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Grab Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
      - name: Install project dependencies
        run: npm ci
      - name: Lint Code
        run: npm run lint
      - name: Test Code
        run: npm run test
      - name: Build Project
        run: npm run build
      - name: Deploy Project
        run: echo "Project Deploied"